version: '3'
services:
    frontend:
        build:
            context: ./
            dockerfile: Dockerfile
        image: js-app:latest
        container_name: js-app
        restart: unless-stopped
        environment:
            - PORT=3000
            - NODE_ENV=production
        ports:
            - 80:3000

